[package]
name = "league_of_lamports"
version = "0.33.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poc-framework = "0.1.6"
anchor-client = "*"
solana-program = "*"
tempfile = "*"
threadpool = "*"
